# This is a basic workflow to help you get started with Actions

name: CI

env:
  ROLE_NAME: tasmota

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:

  workflow_dispatch:

jobs:
  lint:
    name: lint & syntax check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ env.ROLE_NAME }}"
      
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install role requirements
        uses: BSFishy/pip-action@v1
        with:
          requirements: "${{ env.ROLE_NAME }}/requirements.txt"

      - name: Create ansible.cfg
        run: "printf '[defaults]\nroles_path=./tests/requirements/:../' > ${{ env.ROLE_NAME }}/ansible.cfg"

      - name: ansible-lint
        # replace "master" with any valid ref
        uses: ansible/ansible-lint-action@594402913bf720b74acd144d220f25693c61e4fa
        with:
          targets: |
            $ROLE_NAME
          args: "-c ${{ env.ROLE_NAME }}/.ansible-lint"

      - name: ansible-playbook syntax check
        uses: dawidd6/action-ansible-playbook@3c534b3ba0bcbbee2b13fb45226f71acbaca2a76
        with:
          playbook: tests/test.yml
          directory: "${{ env.ROLE_NAME }}"
          requirements: tests/requirements.yml
          options: --syntax-check -i tests/inventory

  galaxy:
    name: ansible-galaxy
    runs-on: ubuntu-latest

    steps:

    - name: import
      uses: robertdebock/galaxy-action@affc5472cd0b08f64a51eafba49b08898c1bbeb8
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}

        
